rhsso:
  name: sso
  replicas: 2
  #hostname: rhsso-hml
  admin: 
    username: sso
    password: sso
  service:
    username: sso
    password: sso
  env:
    database:
      name: mysql
      driver: mysql
      jndi: java:jboss/datasources/KeycloakDS
      username: admin
      password: 123456
      jdbc_url: jdbc:mysql://xyz
      schema: rhsso
      nonxa: true
  resources:
    requests: 
      cpu: 500m
      memory: 2Gi
    limits: 
      cpu: 2
      memory: 6Gi
  imagestream:
    name: sso75-custom
    tag: latest
    namespace: openshift
