{{- if .Values.rhsso }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's https port.
    service.alpha.openshift.io/serving-cert-secret-name: sso-x509-https-secret
  labels:
    application: {{ .Values.rhsso.name | quote }}
  name: {{ .Values.rhsso.name | quote }}
spec:
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    deploymentConfig: {{ .Values.rhsso.name | quote }}
{{- end }}